name: Setup
description: Configure Node.js + pnpm and install dependencies

inputs:
  registry:
    description: NPM registry to set up for auth
    required: false

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: package.json
        registry-url: ${{ inputs.registry }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Get pnpm cache dir
      id: pnpm-cache-dir
      shell: bash
      run: echo "pnpm-cache-dir=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm-cache-dir.outputs.pnpm-cache-dir }}
        key:
          ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install
