name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: SemVer for the release, for example "1.0.0"
        required: true
        type: string

permissions:
  contents: write

jobs:
  check-version:
    name: Check Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.release }}
    steps:
      - name: Check version
        uses: madhead/semver-utils@v4
        id: version
        with:
          version: ${{ inputs.version }}
          lenient: false

  create-version:
    name: Create Version
    runs-on: ubuntu-latest
    needs: check-version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup env
        uses: ./.github/actions/setup

      - name: Bump version
        run: pnpm version --no-git-tag-version '${{ needs.check-version.outputs.version }}'

      - name: Create version commit & tag
        run: |
          author='${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>'
          version='v${{ needs.check-version.outputs.version }}'
          branch='${{ github.ref }}'

          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

          git commit --all --author "$author" --message "$version"

          git tag --annotate "$version" --message "$version"

          git push --atomic origin "$branch" "$version"

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs:
      - check-version
      - create-version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create \
            'v${{ needs.check-version.outputs.version }}' \
            --verify-tag \
            --generate-notes

  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs:
      - check-version
      - create-version
    permissions:
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: refs/tags/v${{ needs.check-version.outputs.version }}

      - name: Setup env
        uses: ./.github/actions/setup
        with:
          registry: https://registry.npmjs.org

      - name: Build
        run: pnpm run build

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        run: |
          pnpm publish \
            --access=public \
            --no-git-checks
